//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdificiosReligiosos
    {
        public int id_edificio { get; set; }
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<System.DateTime> fecha_construccion { get; set; }
        public string denominacion_religiosa { get; set; }
        public string ressenya { get; set; }
        public Nullable<int> id_pais { get; set; }
        public string google_maps_link { get; set; }
        public string web_link { get; set; }
        public string wikipedia_link { get; set; }
        public string imagen_portada_base64 { get; set; }
    
        public virtual Paises Paises { get; set; }
    }
}
