//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeria
    {
        public int id_galeria { get; set; }
        public Nullable<int> id_edificio { get; set; }
        public string imagen_base64 { get; set; }
        public Nullable<bool> Preview { get; set; }
    
        public virtual EdificiosReligiosos EdificiosReligiosos { get; set; }
    }
}
