//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class practicaEdifEntities2 : DbContext
    {
        public practicaEdifEntities2()
            : base("name=practicaEdifEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Continentes> Continentes { get; set; }
        public virtual DbSet<EdificiosReligiosos> EdificiosReligiosos { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
    }
}
