//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_denominacion_religiosa { get; set; }
    
        public virtual EdificiosReligiosos EdificiosReligiosos { get; set; }
    }
}
